### ISSUE TITLE
virtualbox guest additions are out-of-date

### ISSUE THREAD

**Issue by samalloing** [openpreserve/ddhn-forge#12]
Hi @carlwilson (cc @aniamolenda)

If I run dpkg -l | grep virtualbox it states that it uses version 5 of Virtualbox and this ova needs version 6 of Virtualbox). The guest additions don't seem to work as shared clipboard and drag 'n drop don't work. It is user friendly if these features work

Sam

**Comment by samalloing** [comment]
You can integrate it with ansible apparently: https://github.com/PeterMosmans/ansible-role-virtualbox-guest

**Comment by carlwilson** [comment]
Hi @samalloing I think I might try the custom box approach and try to get control over the installation of guest additions on the VM. This could be done alongside #11?
