### ISSUE TITLE
Enable clipbard and drag 'n drop

### ISSUE THREAD

**Issue by samalloing** [openpreserve/ddhn-forge#13]
Hi @carlwilson (cc @aniamolenda)

To make it user friendly clipboard and drap 'n drop should be bidirectional.  Or in vagrant:
`vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]`
`vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]`

Sam

**Comment by carlwilson** [comment]
Agree and will use the vagrant route but need to sort out #12 for this to work reliably.

**Comment by jacobtakema** [comment]
Hi Carl,

I just tested the drag 'n drop and it works.
