### ISSUE TITLE
default password is missing in Quickstart/Readme

### ISSUE THREAD

**Issue by samalloing** [openpreserve/ddhn-forge#14]
Hi @carlwilson (cc @aniamolenda)

The default passwors is missing, but maybe it is better to autologin so no password is required (see one way of doing it: https://help.gnome.org/admin/system-admin-guide/stable/login-automatic.html.en)

Sam

**Comment by carlwilson** [comment]
So autologin might best, for now. I think I can set this up with ansible which is probably easiest.

**Comment by jacobtakema** [comment]
Hi @carlwilson, 

I just started the VM and wasn't asked for a password, so it seems the autologin works fine.
