### ISSUE TITLE
Tools should get icons

### ISSUE THREAD

**Issue by samalloing** [openpreserve/ddhn-forge#15]
Hi @carlwilson (cc @aniamolenda)

Maybe not top priority but icons would make the tools standout.

Sam

**Comment by carlwilson** [comment]
Again I agree, I'd intended to do it but the default GNOME configuration disables this. I was going to raise it at the next call, it's pretty easy to sort via Ansible.

**Comment by jacobtakema** [comment]
Hi @carlwilson 

Shortcuts are available on the desktop screen, looks fancy and handy ;-)
