### ISSUE TITLE
shortcuts on the desktop

### ISSUE THREAD

**Issue by samalloing** [openpreserve/ddhn-forge#16]
Hi @carlwilson (cc @aniamolenda)

Putting some shortcuts on the desktop will make it more usable by first time users. 

Sam

**Comment by carlwilson** [comment]
Similar to #15. At the moments they have *.desktop entries in `/usr/share/applications/` but that's a little at odds with the install location which is at `/usr/local/...`. My intention is to tidy further during the next ansible round, probably my trying to make the apps first-class citizens.

**Comment by jacobtakema** [comment]
Hi @carlwilson 

Just looked at the shortcuts which where added to the desktop-screen. They look nice and handy! ;-)
