### ISSUE TITLE
Graphics controller changing of default setting

### ISSUE THREAD

**Issue by samalloing** [openpreserve/ddhn-forge#17]
Hi @carlwilson (cc @aniamolenda)

In Virtualbox 6, the best Graphics Controller setting for linux seems to be VMSVGA, see the discussion at: https://superuser.com/questions/1403123/what-are-differences-between-vboxvga-vmsvga-and-vboxsvga-in-virtualbox

Sam

**Comment by carlwilson** [comment]
Look at upgrading graphics controller in vagrant task.

**Comment by carlwilson** [comment]
Adopt virtual graphics recommendations from Virtutal Box (these have changed). 2 hours
