### ISSUE TITLE
Use latest version for installing tools

### ISSUE THREAD

**Issue by samalloing** [openpreserve/ddhn-forge#18]
Hi @carlwilson (cc @aniamolenda)

Some tools like jHove and verapdf have urls with the lastest version. Maybe that is easier to add then urls with version numbers. For example jhove: http://software.openpreservation.org/rel/jhove-latest.jar

Sam

**Comment by carlwilson** [comment]
Hi @samalloing, my worry is that we lack control over the version downloaded then. Changing the version details here: https://github.com/openpreserve/ddhn-forge/blob/master/ansible/roles/ddhn.tools/defaults/main.yml#L13 or overriding selected values in your own file should automagically install the updated version.

**Comment by carlwilson** [comment]
Having considered this request we've decided that the "audit" trail of explicit versioning is better for support purposes and ensuring a particular release is consistent (no tool versions updated without our knowledge).
