### ISSUE TITLE
start VM  - change network- vboxnet0 (adapter 2) 

### ISSUE THREAD

**Issue by MerleFri** [openpreserve/ddhn-forge#28]
When first starting the VM I got this errormessage concerning the netinterface:

![StartMessage](https://user-images.githubusercontent.com/30344679/98824559-bd223600-2433-11eb-87d7-6085d055fa89.PNG)

Clicking on the Button "Netzwerkeinstellungen ändern" (change networkconfiguration), switching to "Adapter 2"-tab and pressing ok worked for me and the VM started.  Also clicking "VM beenden" (stop VM) and pressing on start again worked.
If this cannot be changed, this could be mentionned in the user guide.

**Comment by carlwilson** [comment]
Hi @MerleFri, thanks for reporting. Am guessing you're running under windows, it certainly appears so.

**Comment by MerleFri** [comment]
Yes, I am running under Windows.

**Comment by carlwilson** [comment]
@MerleFri there hasn't been a lot of bug reports regarding the network interface configuration so this might be an issue with your set-up. We're putting a maintenance release out in the first quarter and will review this. Would you be happy to test the release candidate to help to reproduce this? 2 hours.
