### ISSUE TITLE
Keyboard layout set to US

### ISSUE THREAD

**Issue by tledoux** [openpreserve/ddhn-forge#30]
The default keyboard layout of the machine is set to US which is very annoying with a french keyboard (AZERTY) for example.

I manage to change it by :
- launching a terminal
- issuing `sudo setxkbmap fr`
but this configuration is not permanent and should be reissued each time the VRE is restarted.

It seems possible, see https://wiki.debian.org/Keyboard, to define multiple keyboard and switch between them with a key combinaison (like Alt+Shift, for example). Haven't been able to master that however...

**Comment by carlwilson** [comment]
There's obviously no perfect choice as default layout but making a permanent change should be possible, again perhaps best added to a getting started guide.

**Comment by carlwilson** [comment]
Fix or close, 2 hours.
