### ISSUE TITLE
xmessage window

### ISSUE THREAD

**Issue by MomoMoses** [openpreserve/ddhn-forge#32]
xmessage window displays on first startup with this error message: "VBoxClient: Failed to get display change request, rc=VERR_TO_BAD_LENGTH

I "X"'d out the window, but it kept popping up later, particularly when I hit "Activities" and the screen formation changed.

**Comment by MomoMoses** [comment]
![2020-11-19 16_49_56-DDHN Beta  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/3534298/99751093-24c92880-2aa7-11eb-8a2c-945e2d498803.jpg)

**Comment by carlwilson** [comment]
Thanks, @MomoMoses this is a duplicate of #24 and I think is due to an unfortunate combination of VBox driver and provisioning mis-step by me. I believe (hope) I have a fix.
