### ISSUE TITLE
Additional Tool: MediaConch

### ISSUE THREAD

**Issue by MerleFri** [openpreserve/ddhn-forge#40]
MediaConch (https://mediaarea.net/MediaConch) can validate LPCM/ffv1/MKV and check any media file for conformance to a (self-made) policy and would thus be a good companion to MediaInfo and Handbrake.

**Comment by carlwilson** [comment]
We will consider this for the next (1st quarter 2022) release, if it's out of scope for that we will include it in a 2rd quarter 2022 release. 2 hours
