### ISSUE TITLE
Read me for dummies

### ISSUE THREAD

**Issue by aniamolenda** [openpreserve/ddhn-forge#5]
While setting up the VM I missed some information for low-entry-level users. Perhaps it should be more clear when a user needs to download and install a piece of software, when to launch terminal and prompt commands etc. Perhaps we need a step by step tutorial as a downloadable PDF that explains it per OS?
These are some issues I noted, which we should keep in mind:
- What do I need to have installed (or install) on my machine for the prototype to run? 
- when to launch the terminal/command line and where to find it (not everyone will know that)
- copy paste commands as step by step
- if a file needs to be modified where to find that file and what exactly to paste where

**Comment by carlwilson** [comment]
I've added a Quickstart section that covers VM download and import with some hints and links. Is that better (see linked PR).
